### ISSUE TITLE
Ubuntu 18.04 install

### ISSUE THREAD

**Issue by paulsheer** [noahgibbs/rails_ruby_bench#16]
Hi,

(edited for errors)

I have followed the instructions [here](https://www.linuxbabe.com/ubuntu/install-discourse-ubuntu-18-04-server-without-docker) to install discourse locally without docker.

I now have discourse running with nginx.

The seed script seems fail due to existing users and then after that with something about categories. I did sql "DELETE from USERS;" and editted seed_db_data.rb to "category:  "Lounge" "

This got it to complete. At the bottom are some discourse edits to get things to work. I hope my json version change doesn't break anything. Can you advise on this please?

Finally I am stuck with a 403 error. Can you help at all with this?

_Got exception when POSTing "/posts"...
Exception in worker thread: 403 Forbidden
/home/paul/.rvm/gems/ruby-2.6.3/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response'
/home/paul/.rvm/gems/ruby-2.6.3/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
/home/paul/.rvm/gems/ruby-2.6.3/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
/home/paul/.rvm/gems/ruby-2.6.3/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
/home/paul/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/net/http.rb:920:in `start'
/home/paul/.rvm/gems/ruby-2.6.3/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
/home/paul/.rvm/gems/ruby-2.6.3/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
/home/paul/.rvm/gems/ruby-2.6.3/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
/home/paul/ruby-test/rails_ruby_bench/user_simulator.rb:53:in `request'
/home/paul/ruby-test/rails_ruby_bench/user_simulator.rb:86:in `action_from_args'
/home/paul/ruby-test/rails_ruby_bench/user_simulator.rb:150:in `block in time_actions'
/home/paul/ruby-test/rails_ruby_bench/user_simulator.rb:149:in `each'
/home/paul/ruby-test/rails_ruby_bench/user_simulator.rb:149:in `time_actions'
/home/paul/ruby-test/rails_ruby_bench/user_simulator.rb:179:in `block (2 levels) in multithreaded_actions'
#<Thread:0x00005654207f3238@/home/paul/ruby-test/rails_ruby_bench/user_simulator.rb:170 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	13: from /home/paul/ruby-test/rails_ruby_bench/user_simulator.rb:179:in `block (2 levels) in multithreaded_actions'
	12: from /home/paul/ruby-test/rails_ruby_bench/user_simulator.rb:149:in `time_actions'
	11: from /home/paul/ruby-test/rails_ruby_bench/user_simulator.rb:149:in `each'
	10: from /home/paul/ruby-test/rails_ruby_bench/user_simulator.rb:150:in `block in time_actions'
	 9: from /home/paul/ruby-test/rails_ruby_bench/user_simulator.rb:86:in `action_from_args'
	 8: from /home/paul/ruby-test/rails_ruby_bench/user_simulator.rb:53:in `request'
	 7: from /home/paul/.rvm/gems/ruby-2.6.3/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
	 6: from /home/paul/.rvm/gems/ruby-2.6.3/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
	 5: from /home/paul/.rvm/gems/ruby-2.6.3/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
	 4: from /home/paul/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/net/http.rb:920:in `start'
	 3: from /home/paul/.rvm/gems/ruby-2.6.3/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
	 2: from /home/paul/.rvm/gems/ruby-2.6.3/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
	 1: from /home/paul/.rvm/gems/ruby-2.6.3/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
/home/paul/.rvm/gems/ruby-2.6.3/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response': 403 Forbidden (RestClient::Forbidden)_

i ran as follows:  (git branch -vv ; git diff ;) | cat | gzip -9 | uuencode -m shell-out.gz

_begin-base64 664 shell-out.gz
H4sIACn9IV4CA6VX63ObSBL/rr+iy/4g6WQQIKFXxbnN2d6c6za2y052ryqX
ogYYpImBYYfBsvdxf/t2D6BHLLtydfogYLqnu6cfv+75G/T+efHuHGKuWbTi
MTAND549smd9iMfc4eFkxDz4matSyBzCKitAy4alA5CxUnMFB37uyI+deTyZ
uvBZKrEU+bBmXkDIVyKPwfW+wI+X/17AnX5KRb6ERCpIONOV4qikEBGgykLJ
RKQcMhmzFHrHs6k37XdikSRgWUuhgQ3f88ywhO1bB8XzR3AnTjKdJv7Es22f
sYSPx+OJC67jTMbjjmVZ272dwWCws/+HH8Aaz04mMMD/GeDnkmfQZZEWDzxA
U3galFwJlorf0DXdE+j+9y049swedTvQqbllzkP5SDQXCXOPKANDWWldWJGU
94LXZIf2DZp9RA1YFPFCBynLlxVb8lqDh4w+vir+ayUUX0DC0pJvFPIs5MpS
TKTGIsd2Z8huDjOZnUxhMHXwvz1MgtEQGcneCGDr0irje6scHVCyz5GXz1ms
2orHSObPiYPDRK2qVnaVJ6+dDY8VKF6kT4FWIsu42njd7R7MBzuV0f02qOaz
yYw5i+d8Npv4zLZDfMaR5/nhwcyot+2lR71Ebp3PKUfw3+TI+4sPnSb7RR7o
leIsLqGHNrr2qN+SMKGXipc1YWQ7J/D2lJ6227DEMqJs7uEmWhvUa3j+PMhZ
hgRMAttz3LkzdVo6AHoPeijJoRw5gTdAWeU0Ig94j8S4tuttOCh3YqaZVcpK
RaiGbPI2ZtcMLQ0VeaRkRCrIE+7YIVe4Y+8bX6wwmLEoSd1k44XVfZzQymhj
4UpnKc+10IIj7xgp4+ZoO8VCPnFISHPmPa+YVPA34p7XEPRM/TQcwp3lJG+y
MQEAczOqlEI7LFWFT03o2hP6LtWQ6/t1Ee1E25SchdZYmmNRIZSRg1zjoP4u
U306pI1tb0evXiHy1cFzx7TLEC0ifS0RA9FwszLYXdn67uta1yxtBt0vhaQV
190EMBXhwwx6U3LsHHmnxGxgDs9DOOfP62OdX9xcXJ1fXJ1dXtx1TPyWK0Rn
3jhj2mhtwtr5JnRk4l7ATqEJ2YtBQbHbuKQCW0Ru3rBKkL5f2RigRCyHlKYh
K7n9lKVYlgdWmzpn85CP/Yk797HOx26MPWk0jffr/NDuutwPUchlI4LRwagB
Uwr5otP2qUXHlDgvGPonKDXTPEPnlBs8A2AxK0wfLGSpCQp+TSnWrZoFoF8j
rLOSB41Q8uoBMgnLMP8zRBN0FepYM5Vj+hkbpEwX4NMrwjyXlcYvx3EOOpTn
D0LJ3Fg6RKVxhZ1O5rYKt254madx9tSPRmwy911st7EXe/4kCafhQWe/ImvP
9a/wUSA8ytwacKhRnLeOWSzeFUUqImaYa1k0VMSS3HEMd1xTlZZQFjwSicC5
Z8WRvhZpCprdc4pgxGOeI9bJBwRLrNCSI6pDYxjbkU9Gk9QbVqVwt+LIzuKY
xwtabtoZdrdlSpqU6bbEfoZTBCAw5lIjVyoZbsHRSK85z802zCtTX7VKO6IB
LYhSVpYIIqd156yh1+DSpAbe73YCMrIQ+8ytmRfQF5irOHKReA043NCxe+8K
0goITzlOcI+1h1hKne0JJaFfRNnfMbKoQlQZUNIGtQyb56QmRovfpzJkaeN8
25CDWmtgtJbwxx+btm9tZNY0+2sZRDIrqHWiOaewaD1ae/87mdHUN6enp+jg
DAMb7wSNxLwu5FMjw875urdYMZXJ/AlO35pQ9Nu4lrrCAitXskopnpRKFolB
l8Q7nmp0NBSUXh/8UHUWVcb2SrFZaOqOe6Np6Exiz7ER21kyxU7lRwfrrt24
V2TtooE2g2wG2DogEri4+vlz9/bd5U93Ab52vwC6rrstxE0y/yhUqU/gSVaQ
c3Qr3hGiFUI8DvIrjpUTYoKvaRU5FJRCV3VaUpjf3dwEt9fXH9EH3eFKZny4
QbjtW5fCs8f5wNRwvV7vsqApeZUFa6nucSpHLjL/6OrTh+CXi3/cHX2xtQwE
4JwAfz9MWsC4PdEdR/fE9ZEihoW/kgQBKzxGxjDs7XinV3hlIiYEfFhKav54
TFXldJUqaTIh+LX3A4vdeFikFV2KRI4lgDhTB/gwoQn0OJ5GYcj8MLFtFvoh
C8OR4+0H+gUBdcBfIFLg/RHh6KB+4ILBGbgxzIvFZcPdDiw7IPNJI3zY/JFH
leZUL+iduNfN7mNhJnSrwH/N1JLr7bxjPuHNG6DRzV6WVdgb/qccnsBRcLTh
OoaP1+fXwNAWznIs3TV7Aplg6S5pSlDkatSFk+/OSj01fY+FKjPmJTvmfffe
NDd76Q7UIB61562gwfH/YcXgf7UiecmMenDPDeyYx/Ms1Ky8L4cNGClqfeHh
9bbJTzw/wd7oz2y8XvoeZqTnjp/n4PP92xR8TjPNfGr6WP2guQq58MJpuBbU
j2uk7BLgPl9ehDyRCql1e9v9iTyRn49KvKkfIX4hVOENjr56BdOr/mHujIp2
y24+a35blHI2cdxv9y1/E0Uj0dqnhErqVBjaCWLH46apbEINm4x/hRe+1Xj3
8fzi9hZbLjbOo3OJI3rLTJVx/Ds14T8R0o5/790oGeG6HdHNNVhSB8bzNKuL
xdlP12f/Cj5cX11/vL66POuDRdOA0n1byQozzev/iRNBVB69YkLnL3IN7IZL
EgAA
====_

**Comment by noahgibbs** [comment]
First, are you using the (admittedly ancient) version of Discourse I do? That's going to be important to the functioning of the script. If you don't, that would give approximately what you see above.

**Comment by paulsheer** [comment]
Hi Noah,

thanks for replying so soon

my git head gives discourse at v2.3.8

i am a bit nervous to try an older version of discourse, because, if anything is broken, then the discourse community is going throw "you should not be using such an old version".

on the other hand I have been struggling for 3 days to get everything working (on account of never before having use gem, ruby, puma, nginx, or discourse)

perhaps i need a break from it and to try again later

**Comment by noahgibbs** [comment]
If this is your first exposure to Ruby, gems, NGinX and so on, this is a *rough* first project :-/ You're likelier to have a *much* easier time if you're willing and able to use the AWS and Packer version with EC2. Is that an option for you?

**Comment by noahgibbs** [comment]
Also, yay for writing books! I've self-published a couple, but nothing through a separate publisher.
