### ISSUE TITLE
Worker exceptions

### ISSUE THREAD

**Issue by mgaudet** [noahgibbs/rails_ruby_bench#3]
There's a chance this is just a side-effect of me trying to run this thing locally, but I'm seeing some exceptions in workers which means I'm not getting any results out: 

```
$ update_discourse.sh 
........................................................................................................................................................................................................
$ ruby start.rb 
Starting and stopping server to preload caches...
Server is started, running start/stop iteration...
In PID 6788, starting server on port 4567
[6788] Puma starting in cluster mode...
[6788] * Version 3.6.0 (ruby 2.3.3-p222), codename: Sleepy Sunday Serenity
[6788] * Min threads: 1, max threads: 6
[6788] * Environment: development
[6788] * Process workers: 10
[6788] * Phased restart available
[6788] * Listening on tcp://0.0.0.0:4567
[6788] Use Ctrl-C to stop
[6788] * Starting control server on tcp://127.0.0.1:9939
[6788] - Worker 3 (pid: 6871) booted, phase: 0
[6788] - Worker 5 (pid: 6879) booted, phase: 0
[6788] - Worker 0 (pid: 6859) booted, phase: 0
[6788] - Worker 1 (pid: 6863) booted, phase: 0
[6788] - Worker 6 (pid: 6883) booted, phase: 0
[6788] - Worker 9 (pid: 6893) booted, phase: 0
[6788] - Worker 2 (pid: 6867) booted, phase: 0
[6788] - Worker 4 (pid: 6875) booted, phase: 0
[6788] - Worker 8 (pid: 6891) booted, phase: 0
[6788] - Worker 7 (pid: 6887) booted, phase: 0
server_stop: Interrupted Rails server at expected PID 6788.
Waiting for dead PID expecting 6788
[6788] - Gracefully shutting down workers...
[6788] === puma shutdown: 2017-05-25 16:17:07 -0400 ===
[6788] - Goodbye!
Got dead pid: 6788
Running start-time benchmarks for 2 iterations...
Server is started, running start/stop iteration...
In PID 7073, starting server on port 4567
[7073] Puma starting in cluster mode...
[7073] * Version 3.6.0 (ruby 2.3.3-p222), codename: Sleepy Sunday Serenity
[7073] * Min threads: 1, max threads: 6
[7073] * Environment: development
[7073] * Process workers: 10
[7073] * Phased restart available
[7073] * Listening on tcp://0.0.0.0:4567
[7073] Use Ctrl-C to stop
[7073] * Starting control server on tcp://127.0.0.1:9939
[7073] - Worker 5 (pid: 7164) booted, phase: 0
[7073] - Worker 0 (pid: 7144) booted, phase: 0
[7073] - Worker 7 (pid: 7172) booted, phase: 0
[7073] - Worker 6 (pid: 7168) booted, phase: 0
[7073] - Worker 4 (pid: 7158) booted, phase: 0
[7073] - Worker 8 (pid: 7176) booted, phase: 0
[7073] - Worker 3 (pid: 7156) booted, phase: 0
server_stop: Interrupted Rails server at expected PID 7073.
Waiting for dead PID expecting 7073
[7073] - Gracefully shutting down workers...
[7152] Early termination of worker
[7180] Early termination of worker
[7148] Early termination of worker
[7073] === puma shutdown: 2017-05-25 16:17:23 -0400 ===
[7073] - Goodbye!
Got dead pid: 7073
Server is started, running start/stop iteration...
In PID 7369, starting server on port 4567
[7369] Puma starting in cluster mode...
[7369] * Version 3.6.0 (ruby 2.3.3-p222), codename: Sleepy Sunday Serenity
[7369] * Min threads: 1, max threads: 6
[7369] * Environment: development
[7369] * Process workers: 10
[7369] * Phased restart available
[7369] * Listening on tcp://0.0.0.0:4567
[7369] Use Ctrl-C to stop
[7369] * Starting control server on tcp://127.0.0.1:9939
[7369] - Worker 6 (pid: 7470) booted, phase: 0
[7369] - Worker 3 (pid: 7457) booted, phase: 0
[7369] - Worker 1 (pid: 7447) booted, phase: 0
[7369] - Worker 9 (pid: 7480) booted, phase: 0
[7369] - Worker 0 (pid: 7443) booted, phase: 0
[7369] - Worker 4 (pid: 7462) booted, phase: 0
[7369] - Worker 2 (pid: 7451) booted, phase: 0
[7369] - Worker 7 (pid: 7474) booted, phase: 0
[7369] - Worker 5 (pid: 7466) booted, phase: 0
[7369] - Worker 8 (pid: 7478) booted, phase: 0
server_stop: Interrupted Rails server at expected PID 7369.
Waiting for dead PID expecting 7369
[7369] - Gracefully shutting down workers...
[7369] === puma shutdown: 2017-05-25 16:17:40 -0400 ===
[7369] - Goodbye!
Got dead pid: 7369
In PID 7662, starting server on port 4567
[7662] Puma starting in cluster mode...
[7662] * Version 3.6.0 (ruby 2.3.3-p222), codename: Sleepy Sunday Serenity
[7662] * Min threads: 1, max threads: 6
[7662] * Environment: development
[7662] * Process workers: 10
[7662] * Phased restart available
[7662] * Listening on tcp://0.0.0.0:4567
[7662] Use Ctrl-C to stop
[7662] * Starting control server on tcp://127.0.0.1:9939
[7662] - Worker 9 (pid: 7779) booted, phase: 0
[7662] - Worker 1 (pid: 7746) booted, phase: 0
[7662] - Worker 6 (pid: 7769) booted, phase: 0
[7662] - Worker 8 (pid: 7777) booted, phase: 0
[7662] - Worker 2 (pid: 7750) booted, phase: 0
[7662] - Worker 3 (pid: 7756) booted, phase: 0
[7662] - Worker 0 (pid: 7742) booted, phase: 0
[7662] - Worker 7 (pid: 7773) booted, phase: 0
[7662] - Worker 5 (pid: 7765) booted, phase: 0
[7662] - Worker 4 (pid: 7761) booted, phase: 0
Warmup iterations: 300
[6759]: Simulating activity for user id -1: system
[6759]: Getting Rails CSRF token...
[6759]: Simulating activity for user id 1: 
[6759]: Getting Rails CSRF token...
[6759]: Simulating activity for user id 2: 
[6759]: Getting Rails CSRF token...
[6759]: Logging in as "system"... (not part of benchmark request time(s))
[6759]: Simulating activity for user id 3: 
[6759]: Getting Rails CSRF token...
[6759]: Simulating activity for user id 4: 
[6759]: Getting Rails CSRF token...
Exception in worker thread: 403 Forbidden
/home/magaudet/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'
/home/magaudet/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
/home/magaudet/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
/home/magaudet/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:853:in `start'
/home/magaudet/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
/home/magaudet/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
/home/magaudet/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
/home/magaudet/open/perf/rails_ruby_bench/user_simulator.rb:53:in `request'
/home/magaudet/open/perf/rails_ruby_bench/user_simulator.rb:78:in `action_from_args'
/home/magaudet/open/perf/rails_ruby_bench/user_simulator.rb:147:in `block in time_actions'
/home/magaudet/open/perf/rails_ruby_bench/user_simulator.rb:146:in `each'
/home/magaudet/open/perf/rails_ruby_bench/user_simulator.rb:146:in `time_actions'
/home/magaudet/open/perf/rails_ruby_bench/user_simulator.rb:172:in `block (2 levels) in multithreaded_actions'
server_stop: Interrupted Rails server at expected PID 7662.
Waiting for dead PID expecting 7662
[7662] - Gracefully shutting down workers...
Exception in worker thread: 500 Internal Server Error
/home/magaudet/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'
/home/magaudet/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
/home/magaudet/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
/home/magaudet/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:853:in `start'
/home/magaudet/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
/home/magaudet/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
/home/magaudet/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
/home/magaudet/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient.rb:65:in `get'
/home/magaudet/open/perf/rails_ruby_bench/user_simulator.rb:44:in `get_csrf_token'
/home/magaudet/open/perf/rails_ruby_bench/user_simulator.rb:138:in `time_actions'
/home/magaudet/open/perf/rails_ruby_bench/user_simulator.rb:172:in `block (2 levels) in multithreaded_actions'

```

rails_ruby_bench: cb358e70fce6f3be97455a29f541134056674702 
Discourse: 20778fbf588339d895ff2641fbf49cc7e968ae9a
Ruby: 2.3.3

**Comment by noahgibbs** [comment]
That commit of rails_ruby_bench should definitely not have the 403s from the CSRF problems. Though maybe you need to run setup or otherwise disable the CSRF check locally?

Check in work/discourse/app/controllers/application_controller.rb. You should see a hash in front of "protect_from_forgery" on line 25. Can you make sure the hash sign is present?

**Comment by mgaudet** [comment]
It is not :) Ok. Lemme try with a fresh directory -- I've definitely been messing about in the pool for long enough things could have been perturbed.

**Comment by mgaudet** [comment]
Oh, that's the other piece. I haven't been using setup.rb as I've never had RVM work for me, and the assumption the benchmark has that it owns the machine was problematic.

**Comment by noahgibbs** [comment]
That makes sense. Then yeah, you (reasonably, understandably) were missing the hack to turn off CSRF in Discourse.

**Comment by mgaudet** [comment]
Awesome. 

Had to turn down the default level of concurrency (the issue I thought I was reporting here. _headdesk_ too many things going on) , but finally got a run done. Thanks!
